"""Gate for the whole renderer: a real script in, a moving, correctly-labelled mp4 out.

Written by the reviewer. Do not edit this file; fix server/ instead.
"""
import os, re, subprocess, sys
sys.path.insert(0, "server")
sys.stdout.reconfigure(encoding="utf-8")

from PIL import Image
import imageio_ffmpeg
import render

FF = imageio_ffmpeg.get_ffmpeg_exe()
OUT = os.path.abspath("verify-render-out")

BRIEF = {"topic": "Kubernetes", "learners": "sinh viên năm nhất",
         "raw": "Giải thích Kubernetes cho sinh viên năm nhất, video ba mươi giây"}
SOURCES = {
    "n01": {"url": "kubernetes.io/docs/concepts/overview/", "trust": "cao",
            "title": "Kubernetes Concepts"},
    "n02": {"url": "cs.stanford.edu/notes/containers", "trust": "trungbinh",
            "title": "Containers"},
}
CLAIMS = {
    "t01": {"text": "Kubernetes điều phối container",
            "evidence": [{"src": "n01", "quote": "Kubernetes orchestrates containers"}]},
    "t02": {"text": "Một cụm gồm nhiều node",
            "evidence": [{"src": "n02", "quote": "A cluster has many nodes"}]},
}
SCRIPT = {
    "sections": [{"no": 1, "name": "Mở đầu"}, {"no": 2, "name": "Cụm và node"}],
    "sentences": [
        {"sec": 1, "chu": "Kubernetes là gì?",
         "loi": "Kubernetes là một hệ thống điều phối container, giúp chạy nhiều bản sao "
                "của cùng một ứng dụng mà không phải bấm tay từng cái.",
         "dur": 9.0, "cls": ["t01"]},
        {"sec": 2, "chu": "Cụm gồm nhiều node",
         "loi": "Một cụm Kubernetes gồm nhiều node, mỗi node là một máy chạy công việc "
                "thật sự của bạn.",
         "dur": 7.0, "cls": ["t02"]},
        {"sec": 2, "chu": "", "loi": "Chúng ta cùng xem một ví dụ cụ thể.",
         "dur": 3.0, "cls": []},
    ],
}

fails = []
meta = render.render(SCRIPT, CLAIMS, SOURCES, BRIEF, OUT, voice="nu", judge=None)

# 1. a playable file of a believable length
if not os.path.exists(meta["path"]):
    fails.append("no video was produced")
if meta["bytes"] < 200_000:
    fails.append("video is only %d bytes" % meta["bytes"])
if meta["seconds"] < 14:
    fails.append("video is %.1fs; three sentences plus two cards cannot be that short"
                 % meta["seconds"])
# Sentences are grouped into held beats now, so the clip count is open + beats + close
# and MUST be fewer than one card per sentence — that was the slideshow.
n_rows = len(SCRIPT["sentences"])
if not 3 <= meta["cards"] <= n_rows + 1:
    fails.append("expected between 3 and %d clips, got %d" % (n_rows + 1, meta["cards"]))
if meta["cards"] >= n_rows + 2:
    fails.append("one card per sentence: the beats are not being grouped")


def probe(p):
    return subprocess.run([FF, "-i", p], capture_output=True, text=True,
                          encoding="utf-8", errors="replace").stderr


info = probe(meta["path"])
if "1920x1080" not in info:
    fails.append("final video is not 1920x1080")
if "Audio:" not in info:
    fails.append("final video has no audio track")


def seconds(p):
    m = re.search(r"Duration: (\d+):(\d+):(\d+\.\d+)", probe(p))
    return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else 0.0


# 2. the camera moves INSIDE one card, away from the fades at either end
clip = os.path.join(OUT, "work", "c001.mp4")
if not os.path.exists(clip):
    fails.append("work/c001.mp4 missing, cannot check the camera")
else:
    d = seconds(clip)
    for t, tag in ((0.7, "early"), (max(1.4, d - 0.7), "late")):
        subprocess.run([FF, "-y", "-v", "error", "-ss", "%.2f" % t, "-i", clip,
                        "-frames:v", "1", os.path.join(OUT, "fr_%s.png" % tag)], check=True)
    a = Image.open(os.path.join(OUT, "fr_early.png")).convert("L").resize((80, 45))
    b = Image.open(os.path.join(OUT, "fr_late.png")).convert("L").resize((80, 45))
    diff = sum(abs(x - y) for x, y in zip(list(a.getdata()), list(b.getdata()))) / (80 * 45)
    if diff < 1.0:
        fails.append("frames 0.7s apart from the fades differ by only %.2f: the card is "
                     "standing still" % diff)

# 3. the words arrive after the picture, rather than the whole frame at once
if os.path.exists(clip):
    band = (120, 280, 1800, 640)
    levels = []
    for t in (0.10, 1.60):
        f = os.path.join(OUT, "tx_%s.png" % t)
        subprocess.run([FF, "-y", "-v", "error", "-ss", str(t), "-i", clip,
                        "-frames:v", "1", f], check=True)
        levels.append(max(list(Image.open(f).convert("L").crop(band).getdata())))
    if levels[1] - levels[0] < 60:
        fails.append("text is already at full strength when the clip starts "
                     "(%d then %d): it is not fading up" % tuple(levels))

# 4. labels are publisher names, never internal ids
if render.publisher(SOURCES["n01"]) != "Kubernetes":
    fails.append("n01 should read Kubernetes, got %r" % render.publisher(SOURCES["n01"]))
if render.publisher(SOURCES["n02"]) != "Stanford":
    fails.append("n02 should read Stanford, got %r" % render.publisher(SOURCES["n02"]))
if render.display_title(BRIEF) != "Kubernetes":
    fails.append("title card should read Kubernetes, got %r" % render.display_title(BRIEF))

if fails:
    print("FAIL")
    for f in fails:
        print(" -", f)
    sys.exit(1)

print("OK: %.1fs, %d clips, %.1f MB, camera moves (diff %.2f), sources named %s"
      % (meta["seconds"], meta["cards"], meta["bytes"] / 1e6, diff,
         ", ".join(render.publisher(SOURCES[s]) for s in meta["sources"])))
